apiVersion: v1
kind: Service
metadata:
  name: ci-cd-pipeline-service
spec:
  selector:
    app: ci-cd-pipeline-project
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 8080
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080  