pipeline{
    agent{
        label "jenkins-agent"
    }
    environment{
        APP_NAME = "ci-cd-pipeline-project"
    }

    stages{
        stage("Cleanup Workspace"){
            steps {
                cleanWs()
            }
        }

        stage("Checkout from SCM"){
            steps {
                git branch: 'main', credentialsId: 'github', url: 'https://github.com/Mykulle/CI-CD-Pipeline-Project'
            }
        }   

        stage("Update the Deployment Tags"){
            steps{
                sh"""
                    cat gitops/deployment.yaml
                    sed -i 's/${APP_NAME}.*/${APP_NAME}:${IMAGE_TAG}/g' gitops/deployment.yaml
                    cat gitops/deployment.yaml
                """
            }
        }

        stage("Push the changed deployment file to Git"){
            steps{
                sh """
                    git config --global user.name "mykulle"
                    git config --global user.email "ducmanh3006@gmail.com"
                    git add gitops/deployment.yaml
                    git commit -m "Update Deployment Manifest"
                """

                withCredentials([gitUsernamePassword(credentialsId: 'github', gitToolName: 'Default')]) {
                    sh "git push https://github.com/Mykulle/CI-CD-Pipeline-Project main"
                }
            }
        }
    }
}
